import {z} from 'zod';import {wrap,user,rate,json,sameOrigin,ai,db,moderate,ApiError} from '@/lib/server';import {roomData,messages,insertMessage} from '@/lib/room';import {validateCitations,validateMessageQuotes} from '@/lib/grounding';import type {Message} from '@/lib/types';
export const POST=wrap(async r=>{sameOrigin(r);const u=await user();await rate(u.userId,'debate',12);const b=z.object({roomId:z.string().uuid(),action:z.enum(['round','summary'])}).parse(await json(r));const room=await roomData(b.roomId);let history=await messages(b.roomId);const record=await db().prepare('SELECT payload FROM reports WHERE id=?').bind(room.reportId).first<{payload:string}>();const report=record?JSON.parse(record.payload):null;
 if(b.action==='summary'){
  if(room.owner!==u.userId)throw new ApiError(403,'방 개설자만 토론을 종료할 수 있습니다.');if(!history.length)throw new ApiError(400,'요약할 발언이 없습니다.');
  const lock=await db().prepare('UPDATE rooms SET closed=2 WHERE id=? AND closed IN (0,1)').bind(room.id).run();if(!lock.meta.changes)throw new ApiError(409,'이미 요약이 진행 중입니다.');
  try{
   history=await messages(room.id);const chosen:{messageId:string;quote:string;author:string;kind:string}[]=[];
   for(let i=0;i<history.length;i+=40){const part=history.slice(i,i+40);const out=z.object({quotes:z.array(z.object({messageId:z.string(),quote:z.string().min(8).max(180)})).min(1).max(3)}).parse(await ai('Select 1-3 verbatim, representative excerpts from this segment of a debate, preserving opposing views. Return {"quotes":[{"messageId":string,"quote":string}]}. Copy exact original text, never translate or summarize a quote. Do not invent a conclusion, action or consensus. Maximum 180 characters per excerpt.',part));chosen.push(...validateMessageQuotes(out.quotes,part))}
   const pages:{heading:string;text:string}[]=[];const pageCount=Math.min(5,Math.max(1,Math.ceil(chosen.length/8)));const perPage=Math.ceil(chosen.length/pageCount);
   for(let i=0;i<pageCount;i++){const prefix=i===0?`전체 ${history.length}개 발언을 검토 대상으로 사용했습니다. 아래는 원문과 대조한 대표 발언 발췌입니다. 참여자 ${new Set(history.map(m=>m.author)).size}개 표시명. 합의·결론·실행 약속을 자동 확정하지 않습니다. AI 발언은 검증된 사실이 아닙니다.\n\n`:'';pages.push({heading:i===0?'토론 기록 · 확인된 발언':'대표 발언 '+(i+1),text:prefix+chosen.slice(i*perPage,(i+1)*perPage).map(q=>`[${q.messageId}] ${q.author}${q.kind==='ai'?' (AI 생성)':''}\n“${q.quote}”`).join('\n\n')})}
   const final={id:crypto.randomUUID(),title:room.title+' · 토론 근거 기록',pages,sources:report?.sources||[],transcript:history.map(({id,author,body,kind,createdAt}:Message)=>({id,author,body,kind,createdAt})),createdAt:new Date().toISOString()};
   await db().batch([db().prepare('INSERT INTO reports(id,owner,title,payload,createdAt) VALUES(?,?,?,?,?)').bind(final.id,u.userId,final.title,JSON.stringify(final),final.createdAt),db().prepare('UPDATE rooms SET closed=1 WHERE id=?').bind(room.id)]);return Response.json(final)
  }catch(e){await db().prepare('UPDATE rooms SET closed=? WHERE id=? AND closed=2').bind(room.closed,room.id).run();throw e instanceof ApiError?e:new ApiError(422,'근거를 확인하지 못해 요약을 보류했습니다. 다시 시도해 주세요.')}
 }
 if(room.closed)throw new ApiError(409,'종료된 토론입니다.');if(history.length>=498)throw new ApiError(409,'토론 한도에 도달했습니다. 요약해 주세요.');if(!report?.sources?.length)throw new ApiError(422,'토론을 뒷받침할 원문이 없습니다.');
 const output=[];for(const role of ['AI · 기회 분석가','AI · 반론 검토자']){
  const out=z.object({citations:z.array(z.object({sourceId:z.string(),quote:z.string().min(12).max(500)})).min(1).max(2),questions:z.array(z.string().min(3).max(250)).min(1).max(2)}).parse(await ai('You are '+role+'. Participate in Korean with evidence and explicitly hypothetical discussion questions only. Return {"citations":[{"sourceId":string,"quote":string}],"questions":[string]}. Quotes must be exact substrings of the ORIGINAL source body, never translations. Do not invent facts, qualifications, forecasts or conclusions. Analyst asks what would support a possible benefit; critic asks what evidence would invalidate assumptions. Questions must not assert an unverified premise. Use at least one supplied source.',{report,history:[...history.slice(-40),...output]}));
  let citations;try{citations=validateCitations(out.citations,report.sources)}catch{throw new ApiError(422,'AI 인용을 원문에서 확인하지 못해 발언을 보류했습니다.')}
  const body='원문 근거\n'+citations.map(c=>`[${c.sourceId}] “${c.quote}”`).join('\n')+'\n\n검토 질문 (AI가 제안한 가설이며 사실 주장이 아닙니다)\n'+out.questions.map(q=>'• '+q).join('\n');await moderate(body);output.push(await insertMessage(room.id,u.userId,role,body,'ai'));
 }
 return Response.json(output)
});
