'use client';
import {useRef,useEffect,useState} from 'react';
import {Compass,GitCompareArrows,FileText,MessagesSquare,UserRound,ArrowUpRight,Globe2} from 'lucide-react';
const destinations=[{id:'sources',title:'커뮤니티 지도',en:'ATLAS',description:'국경 없이 펼쳐진 대화',icon:Globe2,x:49,y:17},{id:'explore',title:'탐색',en:'EXPLORE',description:'세계의 목소리를 발견하다',icon:Compass,x:23,y:30},{id:'compare',title:'관점 비교',en:'PERSPECTIVES',description:'다른 생각 사이의 연결',icon:GitCompareArrows,x:72,y:24},{id:'reports',title:'보고서',en:'RESEARCH',description:'흩어진 의견에서 얻은 통찰',icon:FileText,x:83,y:67},{id:'community',title:'토론',en:'ROUNDTABLE',description:'더 깊은 대화가 시작되는 곳',icon:MessagesSquare,x:48,y:79},{id:'profile',title:'마이페이지',en:'MY UNIVERSE',description:'나의 기록과 대화의 궤적',icon:UserRound,x:15,y:69}];
export function Constellation({onNavigate}:{onNavigate:(id:string)=>void}){
 const [entering,setEntering]=useState<string|null>(null);const [origin,setOrigin]=useState('50% 50%');const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 function enter(id:string,e:React.MouseEvent<HTMLButtonElement>){if(entering)return;const rect=e.currentTarget.parentElement!.getBoundingClientRect();const button=e.currentTarget.getBoundingClientRect();setOrigin(`${button.x+button.width/2-rect.x}px ${button.y+button.height/2-rect.y}px`);setEntering(id);timer.current=setTimeout(()=>onNavigate(id),window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:650)}
 return <section className={'universe '+(entering?'entering':'')} aria-label="VMAX 별자리 메뉴"><div className="universe-heading"><span className="eyebrow">A UNIVERSE OF PERSPECTIVES</span><h1>모든 관점이 만나는 우주.</h1><p>당신의 다음 발견은 어디에서 시작될까요?</p></div><div className="constellation" style={{transformOrigin:origin}}><div className="constellation-grid" aria-hidden="true"/><div className="universe-center" aria-hidden="true"><span className="center-cross">+</span><span>VMAX</span><small>EVERY VOICE. CONNECTED.</small></div><svg className="constellation-lines" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M23 30 L72 24 L83 67 L48 79 L15 69 L23 30 M23 30 L48 79 M72 24 L48 79"/></svg>{destinations.map((d,i)=><button key={d.id} className={'star-destination star-'+i+(entering===d.id?' chosen':'')} style={{'--x':d.x+'%','--y':d.y+'%','--delay':i*.5+'s'} as React.CSSProperties} onClick={e=>enter(d.id,e)} disabled={!!entering} aria-label={d.title+' 열기'}><span className="star-core"><d.icon size={24}/></span><span className="star-caption"><span className="star-number">0{i+1} / {d.en}</span><strong>{d.title}<ArrowUpRight size={16}/></strong><small>{d.description}</small></span></button>)}</div><div className="universe-footer"><span><i/> 하나의 주제, 무한한 관점</span><span>별을 선택해 탐험하세요</span></div><div className="warp-flash" aria-hidden="true"/></section>
}
export function Starfield(){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;const draw=()=>{const ratio=Math.min(window.devicePixelRatio||1,2);const w=window.innerWidth,h=window.innerHeight;canvas.width=w*ratio;canvas.height=h*ratio;ctx.scale(ratio,ratio);ctx.clearRect(0,0,w,h);let seed=7141;const rand=()=>{seed=(seed*16807)%2147483647;return seed/2147483647};for(let i=0;i<180;i++){const x=rand()*w,y=rand()*h,r=rand()<.08?1.5:.5+rand()*.4;ctx.fillStyle=`rgba(${i%5===0?'115,166,255':'211,226,255'},${.16+rand()*.6})`;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}};draw();window.addEventListener('resize',draw);return()=>window.removeEventListener('resize',draw)},[]);return <canvas ref={ref} className="starfield" aria-hidden="true"/>}
