import type { Post } from './types';
// Hand-authored UX fixtures. These are not scraped posts or real user quotations.
export const demoPosts:Post[]=[
{id:'demo-1',title:'AI 반도체의 다음 성장 구간, 수요가 실적으로 이어질까?',body:'데이터센터 투자가 이어진다면 반도체의 장기 수요를 긍정적으로 볼 수 있다. 다만 실제 매출 전환 속도를 확인해야 한다.',translation:'',language:'ko',source:'한국어 커뮤니티 · 예시',url:'',publishedAt:'2026-09-15T08:00:00Z',sentiment:'positive',stance:'AI 인프라 수요 확대',demo:true},
{id:'demo-2',title:'The AI infrastructure thesis still has room to run',body:'Enterprise adoption could support demand beyond the initial buildout. Utilization and recurring orders matter more than a single earnings headline.',translation:'기업의 AI 도입이 초기 인프라 구축 이후에도 수요를 뒷받침할 수 있다. 단기 실적보다 가동률과 반복 주문이 중요하다.',language:'en',source:'영어 커뮤니티 · 예시',url:'',publishedAt:'2026-09-15T07:00:00Z',sentiment:'positive',stance:'AI 인프라 수요 확대',demo:true},
{id:'demo-3',title:'Une croissance déjà intégrée dans les cours ?',body:'La demande est réelle, mais la valorisation suppose une exécution presque parfaite. Le risque vient surtout des attentes.',translation:'수요는 실재하지만 현재 가치평가에는 거의 완벽한 실행이 반영돼 있다. 기대 수준이 주요 위험이다.',language:'fr',source:'프랑스어 커뮤니티 · 예시',url:'',publishedAt:'2026-09-15T06:00:00Z',sentiment:'negative',stance:'높은 가치평가 부담',demo:true},
{id:'demo-4',title:'성장은 인정하지만 지금 가격에는 신중해야 한다',body:'반도체 업황 회복만으로 높은 기대를 모두 충족할 수 있을까? 공급 증가와 경쟁 심화가 마진에 미치는 영향을 함께 봐야 한다.',translation:'',language:'ko',source:'한국어 커뮤니티 · 예시',url:'',publishedAt:'2026-09-15T05:00:00Z',sentiment:'negative',stance:'높은 가치평가 부담',demo:true},
{id:'demo-5',title:'Watch the orders, not the narrative',body:'I would wait for order visibility and margins before taking a view on AI chip demand. Growth alone does not settle the valuation question.',translation:'AI 반도체 수요를 판단하기 전에 주문 전망과 마진을 확인하겠다. 성장만으로 가치평가 논쟁이 해결되지는 않는다.',language:'en',source:'영어 커뮤니티 · 예시',url:'',publishedAt:'2026-09-15T04:00:00Z',sentiment:'neutral',stance:'실적 확인 필요',demo:true},
{id:'demo-6',title:'AI半導体、需要と利益を分けて考える',body:'需要の拡大だけでなく、設備投資の回収と利益率を確認したい。',translation:'수요 확대뿐 아니라 설비투자의 회수와 이익률을 확인하고 싶다.',language:'ja',source:'일본어 커뮤니티 · 예시',url:'',publishedAt:'2026-09-15T03:00:00Z',sentiment:'neutral',stance:'실적 확인 필요',demo:true}
];
